### ISSUE TITLE
How to build and install it?

### ISSUE THREAD

**Issue by nandni22jain** [shkmr/cp2130#1]
`make -C /lib/modules/`uname -r`/build M=$PWD `
this shows no error, but there is no .KO file or .o file created 

`make` 
this shows no error, but only .o file is created not .ko file.

**Comment by shkmr** [comment]
Hello,

This is user mode driver.  You do not need kernel module.

However, you will need an external library called libusb.
This is popular library and you will find it in your linux package system.
In my linux box,  I did (if I remember correctly)

$ sudo yum install libusb

to install libusb.

The Makefile in the git repo is configured for libusb-0.1,
but above yum command most likely installs libusb-1.0.
If it is the case,  you will also need to edit Makefile.
Comment out settlings for libusb-0.1 and uncomment settings for libusb-1.0.

$ make

will make two test programs:  test_cp2130 and test_cp2130ek.

If you happened to have the evaluation kit (CP2130EK), plug it in and
run test_cp2130ek with root privilege. 

$ sudo ./test_cp2130ek

* will move as you rotate potentiometer on the CP2130EK.

If it works, libcp2130 is ready for your own project.

99-silabs.rules is an example of udev rule, it will allow all the devices with VendorID=0x10c4
to be used without root privilege.

**Comment by nandni22jain** [comment]
Hii,

Thank you for the clarification.
